on:
  pull_request:
    branches:
      - master
  issue_comment:
    types:
      - created

permissions:
  issues: write

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Autoformat happy path
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test autoformat
        uses: ./ # Uses an action in the root directory
        with:
          project: test-project/
      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
